steps:
  # Set up Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/cts01-pratikkamble/docker-fun/flask-color-change:$COMMIT_SHA'
      - '.'

  # Push the resultant Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/cts01-pratikkamble/docker-fun/flask-color-change:$COMMIT_SHA'

images:
  - 'us-central1-docker.pkg.dev/cts01-pratikkamble/docker-fun/flask-color-change:$COMMIT_SHA'
